Adding a more human readable format for last login
DOWRIGHTTV/DNX-FWALL-CMD pull request #6
Opened 2020-11-10 14:38 UTC by Microwave22

I saw the note about making the last_login a more human readable format so I did it.

2020-11-10 14:43 UTC, Microwave22 commented on dnx_frontend/dfe_dnx_main.py
> +            # session['expire_time'] = + 30
Don't know remember doing this but it shouldn't affect anything.

2020-11-10 14:43 UTC, Microwave22 commented on dnx_frontend/dfe_dnx_main.py
> +            last_login = datetime.datetime.now()
I found that putting datetime into a variable helps. Don't know why just what I have seen.

2020-11-10 14:43 UTC, Microwave22 commented on dnx_frontend/dfe_dnx_main.py
> +                'logged_in': last_login,
Replacing the old confusing time with a new human readable one.

2020-12-13 01:50 UTC, DOWRIGHTTV requested changes
thanks for taking time to put a PR in! in this case, the human readable needs to be string format/ serializable since the "stored_tracker" object gets serialized into json and written to disk. if i remember correctly datetime has methods to convert to string somewhat easily with a formatting string.

2021-07-21 14:01 UTC, closed without merging